# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build_and_Run
    displayName: Build_and_Run
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/bulletin-board-app/Dockerfile'
        tags: |
          $(tag)
    - task: CmdLine@2
      displayName: Build and run an image
      inputs:
        script: scripts/build-and-run
        workingDirectory: ./
    - task: PublishBuildArtifacts@1
      inputs:
        TargetPath: $(System.DefaultWorkingDirectory)/bin/node-bulletin-board/bulletin-board-app/Dockerfile
        artifactName: testArtifactDockerfile